- hosts: all
  gather_facts: false

  pre_tasks:
  - name: Install python2 for Ansible
    raw: test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
  - name: Gathering Facts
    setup: