all:
  children:
    webserver:
      hosts:
        178.62.40.54:
          node: client
      vars:
        ansible_user: root                
    master:
      hosts:
        178.62.26.109:
          node: server
      vars:
        ansible_user: root
    cloud:
      hosts:
        178.62.26.109: 
        178.62.40.54: 
      vars:
        ansible_user: root                     